"""Add user_to_budget table.

Revision ID: c74799250b38
Revises: 7d0252e2e6fc
Create Date: 2022-11-01 22:08:23.043257

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "c74799250b38"
down_revision = "7d0252e2e6fc"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_to_budget",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("budget_id", sa.Integer(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["budget_id"], ["budget.id"], name="user_to_budget_budget_fk"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], name="user_to_budget_user_fk"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_to_budget")
    # ### end Alembic commands ###
